nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@husky-install/plugin-install-husky.cjs

yarnPath: .yarn/releases/yarn-3.3.1.cjs

#
# zip/checksum behaviour is platform-specific (e.g. Windows vs Linux) for github: repos
# e.g. packages/libs/components import of tidytree
# see https://github.com/yarnpkg/berry/issues/5795
#
checksumBehavior: ignore
