checksumBehavior: ignore

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# Legacy deployment support: allows Yarn 1.x to bootstrap to Yarn 3.3.1
# Development machines should set YARN_IGNORE_PATH=true to use corepack instead
yarnPath: .yarn/releases/yarn-3.3.1.cjs

# Prevent accidental lockfile modifications - yarn.lock must be committed to git
# Commands like 'yarn add' and 'yarn remove' work normally, but plain 'yarn install'
# will fail if it would modify the lockfile. This prevents accidental mass upgrades
# (e.g., regenerating yarn.lock would upgrade many packages to newer versions).
# All dependency upgrades should be intentional and reviewed.
enableImmutableInstalls: true