checksumBehavior: ignore

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# Prevent accidental lockfile modifications - yarn.lock must be committed to git
# Commands like 'yarn add' and 'yarn remove' work normally, but plain 'yarn install'
# will fail if it would modify the lockfile. This prevents accidental mass upgrades
# (e.g., regenerating yarn.lock would upgrade many packages to newer versions).
# All dependency upgrades should be intentional and reviewed.
enableImmutableInstalls: true