checksumBehavior: ignore

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# Supply chain security: require packages to be at least 7 days old before installation
npmMinimalAgeGate: 10080
