# web-monorepo

## Prerequisties
* `Node <=16.17.1`
* Either a global installation of `yarn >=1.17.0`, or `volta >=1.1.0`
** With such a version of `yarn` globally installed, all `yarn` commands executed in this repo will be delegated to the "pinned" `yarn@3.3.1` installation included in `.yarn/releases`.
** With such a version of https://volta.sh/[volta] installed, the required version of `yarn` will automatically be installed.

## Quick Start

### Install yarn dependencies

From anywhere in the repo:

```
yarn
```

### View workspace dependency graph

From the root `package.json`:

```
yarn nx graph
```

### Execute a workspace's yarn script using the `nx` task runner

From the root `package.json`:

```
yarn nx run <workspaceName>:<scriptName>
```

For example, you can start the MultiBLAST dev server by running

```
yarn nx run @veupathdb/multi-blast:start
```

### Rebuild dependencies when running a development server

When running a development server (such as `yarn nx start @veupathdb/eda` or `yarn nx start @veupathdb/clinepi-site`),
use the following command to rebuild changes made to dependencies, and to have the dev site reload with the changes:

```
cd packages/libs/<package>
yarn build-npm-modules
```

**Note: You may need to manually reload your website to see the changes the first time.**

_Using the equivalent `nx` command (`yarn nx build-npm-modules @veupathdb/<package>`) has proven inadequate in this scenario._

## Notes on individual packages

### EDA dev server

Directory: `packages/libs/eda`

You will need to configure the server with a `packages/libs/eda/.env.local` file that sets various environment variables.

For more documentation see the link:packages/libs/eda/README.md[package README] and link:packages/libs/eda/.env.local.sample.localservices[this sample file].

### VEuPathDB sites

Directory: `packages/sites/{site name}-site`

Copy the `packages/sites/{site name}-site/.env.sample` file to `packages/sites/{site name}-site/.env` and configure the new file with passwords and the desired backend for the site.

Run `yarn` to update dependencies if necessary.

Run the command `yarn nx start @veupathdb/{site name}-site`. For example, to run the ortho site use `yarn nx start @veupathdb/ortho-site`.

## IDE hints

### emacs tide

If it is showing errors for tsx imports (especially in `eda`) and
`tide-verify-setup` mentions tsserver version 3.x then it is time to
upgrade emacs tide (to, at time of writing 4.5.4):

```
M-x package-reinstall <ret> tide <ret>
```

== Docker Image

This repo contains a Dockerfile that may be used to build and run an NGINX
server that serves out the compiled client bundles.

The docker image may be built using the command `make docker-build` and run
using the command `make docker-run`.  The files are exposed under the paths in
the following blocks.

=== Redirecting Paths

These paths are the "primary" URI paths that client code will reference.  The
backing NGINX server will redirect to one of the <<Static Paths>> based on the
requesting browser version with a `301` HTTP status code.

[source]
----
{URL}/clinepi/{file-name}
{URL}/genomics/{file-name}
{URL}/mbio/{file-name}
{URL}/ortho/{file-name}
----

==== Browser Versions

The following table describes what versions of which browsers will be redirected
to `legacy` paths or `modern` paths.

[%header, cols="2,1,2m"]
|===
| Browser     | Versions | Path Prefix
| MSIE        | 1-9      | legacy
| Firefox     | 1-31     | legacy
| Opera       | 0-21     | legacy
| Safari      | 0-6      | legacy
| Chrome      | 0-33     | legacy
| * (default) | *        | modern
|===

=== Static Paths

These paths are the static, non-redirecting paths to the files hosted by the
NGINX server.

[source]
----
{URL}/legacy/clinepi/{file-name}
{URL}/modern/clinepi/{file-name}

{URL}/legacy/genomics/{file-name}
{URL}/modern/genomics/{file-name}

{URL}/legacy/mbio/{file-name}
{URL}/modern/mbio/{file-name}

{URL}/legacy/ortho/{file-name}
{URL}/modern/ortho/{file-name}
----

The ""

So for example, after running `make docker-run`, the URL
http://localhost:8082/genomics/site-client.bundle.js may be used to fetch
the `site-client.bundle.js` file.