name: Debug GitHub Context
on:
  push:
    branches:
      - bob-action-debugging

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context
        run: echo '${{ toJson(github) }}'
